version: '3.4'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine
    
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ..
      dockerfile: Basket.Api/Dockerfile
  
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: ..
      dockerfile: Ordering.Api/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine

  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: ..
      dockerfile: Authentication.Api/Dockerfile

volumes:
  mongo_data:


